### ISSUE TITLE
Dangerous bitwise manipulation in nodetello.js

### ISSUE THREAD

**Issue by dolphin-wood** [SovGVD/nodetello#1]
The following code https://github.com/SovGVD/nodetello/blob/66ae74e9f6c57d51f9d4c1e0677c44f8ed95efaf/lib/nodetello.js#L408-L410

is considered **potentially dangerous** because:

1. All numbers in JavaScript are represented as `double`<sup>[1](https://tc39.github.io/ecma262/#sec-terms-and-definitions-number-value)</sup>, which means you can only have integers in the range [−2<sup>53</sup>, +2<sup>53</sup>],
2. (Most important) bitwise operators treat their operands as a sequence of 32 bits<sup>[2](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Bitwise_Operators)</sup> and return a signed 32-bit integer<sup>[3](https://tc39.github.io/ecma262/#sec-left-shift-operator-runtime-semantics-evaluation)</sup>, so the code `(fast << 44) | (yaw << 33)` will not work as expected. (Actually, you can try `1 << 32` and see how it goes)

Since this code is used to control the drone, IMO it's really dangerous and may hurt users. How do you think?

Refs:

1. [Number value - ECMAScript Latest Draft (ECMA-262)](https://tc39.github.io/ecma262/#sec-terms-and-definitions-number-value)
2. [Bitwise operators - MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Bitwise_Operators)
3. [The Left Shift Operator - ECMAScript Latest Draft (ECMA-262)](https://tc39.github.io/ecma262/#sec-left-shift-operator-runtime-semantics-evaluation)

**Comment by SovGVD** [comment]
Oh. Sorry, just saw it. This code was not used to control (copy-paste from PyTello library) and has been removed as I'm begin working on drone control.

**Comment by ruswerner** [comment]
I'm putting this out there in case someone else arrives here like I did. The follow code works properly on node 10.4+ and was converted (by me) from TelloLib. This produces the same result as the base-2 string method in this repo.

    const axis1 = BigInt(parseInt(660.0 * stickData.roll + 1024.0));
    const axis2 = BigInt(parseInt(660.0 * stickData.pitch + 1024.0));
    const axis3 = BigInt(parseInt(660.0 * stickData.throttle + 1024.0));
    const axis4 = BigInt(parseInt(660.0 * stickData.yaw + 1024.0));
    const axis5 = BigInt(parseInt(660.0 * stickData.speed + 1024.0));

    const packedAxis =
      (axis1 & 0x7ffn) |
      ((axis2 & 0x7ffn) << 11n) |
      ((0x7ffn & axis3) << 22n) |
      ((0x7ffn & axis4) << 33n) |
      (axis5 << 44n);

    console.log(`packed`, packedAxis.toString(2), packedAxis.toString(2).length);

I'm am unsure of the speed of this versus doing string processing, but I have to assume it's faster and more efficient.

**Comment by ruswerner** [comment]
Updated the code snippet above to `parseInt()` before passing to `BigInt` because the stick data values are floats and `BitInt` requires integer values.
